### ISSUE TITLE
User Stories - Brainstorm

### ISSUE THREAD

**Issue by SavageWilliam** [FAC9/childline-yoti#1]
Overall user journey

As an under 18 (CYP)...
I want to report an explicit online image to IWF (internet watch foundation)...
So that it can be removed as quickly as possible...

**Comment by SavageWilliam** [comment]
As a CYP...
I want to prove that I'm under 18...
So that IWF can legally handle my case...

**Comment by SavageWilliam** [comment]
As a CYP...
I want to remain anonymous...
So that I feel comfortable reporting the image...

**Comment by SavageWilliam** [comment]
As a CYP...
I want to understand if my image fits the criteria for removal...
So that I am reassured that I am 'in the right place'...

**Comment by SavageWilliam** [comment]
As a CYP...
I want to be presented with alternatives locations for help/advice...
If my image doesn't fit the criteria for removal...

**Comment by SavageWilliam** [comment]
As a CYP...
I want to easily (and securely) send the image address...
So that it can be removed and only seen by the IWF...

**Comment by SavageWilliam** [comment]
As a CYP...
I want to see information on what happens after submitting my request...
So that I understand what to expect next (& how long it might take...

**Comment by SavageWilliam** [comment]
As a CYP...
I want an an option to submit more than one address...
So that I can submit multiple location (if applicable) to IWF...

**Comment by SavageWilliam** [comment]
As a CYP...
I would like to track my case's progress...
So that I know when its finished/if it has been removed...

**Comment by SavageWilliam** [comment]
As a CYP...
I want to see other options if the image can't be removed...
So that I can take other actions to get the image taken down...

**Comment by SavageWilliam** [comment]
As a CYP...
I want to be see a confirmation message...
So that I know my request has been sent AND what to expect next...

**Comment by denesnori** [comment]
They are both on the readme and each user story has its own issue too
