### ISSUE TITLE
fonts  

### ISSUE THREAD

**Issue by SavageWilliam** [FAC9/childline-yoti#11]
@jenlittle (I can't assign Lizzie just yet)

If you were able to get the exact fonts that Childline uses on their website that would be great! 

I've tried to get these myself from the site but it appears its often called 'Childline-Regular'

**Comment by jenlittle** [comment]
Hi Will,

I have attached these for you - let me know if they don't come through on github

J
________________________________

**Comment by jenlittle** [comment]
[Childline Web.zip](https://github.com/FAC9/childline-yoti/files/758962/Childline.Web.zip)

**Comment by SavageWilliam** [comment]
@jenlittle Thanks! got the fonts and have them working.. I noticed there are also

**Comment by SavageWilliam** [comment]
@jenlittle Awesome! Thanks.

We're excited to give it a childline feel..

Having a technical issue using the font... my browser is unable to 'decode' the font which suggests the files you sent are broken. 

Would also be great to get the Rosie font file!

**Comment by jenlittle** [comment]
[Childline Fonts.zip](https://github.com/FAC9/childline-yoti/files/760611/Childline.Fonts.zip)

**Comment by jenlittle** [comment]
@SavageWilliam give that a go, fingers crossed you can get to Rosie in there :)

**Comment by SavageWilliam** [comment]
@jenlittle So we have the childline fonts working nicely.. the Rosie font is a little broken. It's only rendering A couple of capital letters

**Comment by jenlittle** [comment]
@SavageWilliam that is really annoying, I don't know why that would be...we gave it to some other devs just before Christmas and it was OK. Could you send over a screenshot or some details of which ones are/aren't working so I can check with our designer?

**Comment by SavageWilliam** [comment]
@jenlittle  Hopefully from the images below you can see whats happening.. some letters seem to make it. Most of them do not 😄 

![image](https://cloud.githubusercontent.com/assets/15717822/22746411/82dfc54a-ee1b-11e6-9779-d30e8c20bfa5.png)

![image](https://cloud.githubusercontent.com/assets/15717822/22746391/78c23660-ee1b-11e6-9880-0c3c8b2a745e.png)

**Comment by jenlittle** [comment]
Thinking about it @SavageWilliam we did have to supply something a little different to someone else - does any of this help!?!
[webfontkit-20161027-075048.zip](https://github.com/FAC9/childline-yoti/files/761288/webfontkit-20161027-075048.zip)

**Comment by SavageWilliam** [comment]
@jenlittle Strangely enough getting the same issue with these files! 

Might be out of my depth.. I have limited font experience. But have tried all of those last few you sent.

**Comment by SavageWilliam** [comment]
@jenlittle  RESOLVED 💃 

Turns out its a font for caps lock only.. hehe, should have realised

**Comment by jenlittle** [comment]
Woohoo! Ah yes, I should have remembered/mentioned the all caps-ness. Not ideal for accessibility but the brand is quite rigid on that. Thank!
