### ISSUE TITLE
IWF and Childline - history

### ISSUE THREAD

**Issue by jenlittle** [FAC9/childline-yoti#17]
History of the partnership between the IWF and Childline: https://www.iwf.org.uk/news/childline-and-internet-watch-foundation-form-new-partnership-to-help-young-people-remove

The IWF "hash list": https://www.iwf.org.uk/become-a-member/services-for-members/image-hash-list

**Comment by SavageWilliam** [comment]
This issue was moved to childline-yoti/online-content-reporter#5
