### ISSUE TITLE
Bullet points for "Does your image meet the criteria?" question.

### ISSUE THREAD

**Issue by denesnori** [FAC9/childline-yoti#21]
Please tell us what  bullet points you would like to see under this question.

**Comment by jenlittle** [comment]
@lizziesumner is working on this with our content team and will update you when we have something a little more CYP friendly than the current info

**Comment by lizziesumner** [comment]
Our content team have made the wording a little more suitable for the audience:

"If you come across a sexual image of a young person, or if you’ve sent a naked or sexual picture or video and you want it removed, we can help.

Select the option(s) below to tell us what the picture or video includes:

•	someone posing in a sexual way
•	someone touching themselves in a sexual way
•	any sexual activity involving a child, adult or both
•	someone hurting someone else
•	sexual activity that includes animals.

If the picture or video doesn't include any of the activities above, we may not be able to remove it. [Talk to a Childline counsellor for more advice](https://www.childline.org.uk/get-support/1-2-1-counsellor-chat/)"

**Comment by denesnori** [comment]
Thanks :)
