### ISSUE TITLE
progress after day 1

### ISSUE THREAD

**Issue by SavageWilliam** [FAC9/childline-yoti#43]
@jenlittle @lizziesumner @njsfield - Have a look at these screen grabs of the prototype as it is at the end of day 1 of design sprint. 

Tomorrow (thursday) will be our last full day to make real changes... so post some comments/feedback on this issue as early in the day as possible and we'll address them!

Two main areas to give particular consideration:
- content/wording (current and missing)
- Style/UX (colours, shapes, buttons, links)

*The final form for submiting url is still in progress @denesnori*

![image](https://cloud.githubusercontent.com/assets/15717822/22761215/b370bdfa-ee51-11e6-8b47-e305f5a9aed2.png)

![image](https://cloud.githubusercontent.com/assets/15717822/22761306/1765e0ec-ee52-11e6-8143-4a57e4de7384.png)

![image](https://cloud.githubusercontent.com/assets/15717822/22761329/2c58008e-ee52-11e6-8898-eaeac654525e.png)

![image](https://cloud.githubusercontent.com/assets/15717822/22761396/6763afac-ee52-11e6-9e0e-d9834debce95.png)

> same page...

![image](https://cloud.githubusercontent.com/assets/15717822/22761414/73bf15fc-ee52-11e6-8074-406356979788.png)

![image](https://cloud.githubusercontent.com/assets/15717822/22761226/c4d5150a-ee51-11e6-8f3f-9b0bc2f0644b.png)

**Comment by SavageWilliam** [comment]
I can see one wording issue:

'describe the image content'  - I think we need to keep this open to all kinds of online media? Aka Videos? 

'describe the online content'

**Comment by njsfield** [comment]
Great work! You've put a lot of great effort into utilising the existing style guide and I think the content descriptions are very carefully worded and work well.

A few personal UI thoughts- perhaps keep the title fonts consistent, make 'Report Content Online' use the same font as on other pages (Rosie font?), 

I would remove the share icon in the right of the 'Report Content' button as its role as a button is already quite clear (no need for icon), and the share icon is more recognised as an icon to share icon (via email, Facebook, twitter etc). 

Other than that horizontally centre the 'confirm' button.

Great work and looking forward to seeing the final prototype! :)

**Comment by SavageWilliam** [comment]
If possible we should make our buttons the same as [childline's](https://www.childline.org.uk/) 

They have a slight shadow underneath.. and raise 'up' on hover. @njsfield Are you around today for any hands on assistance? 😀

**Comment by jenlittle** [comment]
@SavageWilliam @denesnori this is looking great - @lizziesumner is working up our comments for the call in a bit - we can call in to our conference link if you like?:

Join by Phone
Number: +442037729400
Conference ID: 8195672

**Comment by SavageWilliam** [comment]
@jenlittle Sounds good. We'll call at 10.30? Do we give that ID after calling that number?

**Comment by jenlittle** [comment]
Great, that works for us @SavageWilliam. Yes when you ring that number it’ll ask for an ID and you just put that in followed by # I think (it’ll talk you through it)

Speak to you in a bit!

**Comment by lizziesumner** [comment]
We've collated all our feedback so thought it would be helpful to share ahead of the call, then we can discuss anything that isn't clear:

**Screen 1**

•	All titles to use Rosie font
•	Lower case C on confidentially (e.g. Anonymously and confidentially)
•	All boxes the same width
•	Upper case R on Report content
•	Keep link out icon

**Screen 2**

•	All blocks to be the same width
•	Title: “Are you under 18?”
•	Progress tracker could be clearer by using numbers or delineation for each step e.g. https://www.childline.org.uk/registration with numbers
•	Can we add some explanatory copy under the progress tracker such as: "To remove explicit online content we need to confirm that you are under 18"
•	We only use red for warnings, can we change red boxes to purple?
•	Can we add an additional box for "Other ways to prove your age" (just in case they don't want to use Yoti)

**Screen 3** 

•	All boxes same width
•	Replace red with purple

**Screen 4**

•	Title box: Can the red be replaced with dark blue?
•	Title: Describe the online content
•	All boxes to be the same width
•	Centre ‘Confirm’ button
•	Hyperlink "Talk to a Childline counsellor"

**Screen 5**

•	Can we replace red with the other colours in the palette?
•	Copy: "You must be under 18”
•	 Copy: "Unfortunately we are not legally able..."
•	Other options for contact:

-	Contact CEOP [https://www.ceop.police.uk/CEOP-Reporting/]
-	Contact The Mix [http://www.themix.org.uk/]
-	Contact the Samaritans [http://www.samaritans.org/]

**Comment by denesnori** [comment]
Thanks for the feedback. :) We will send you an updated version later today :)

**Comment by SavageWilliam** [comment]
![image](https://cloud.githubusercontent.com/assets/15717822/22781990/0298487e-eebd-11e6-8c55-52447c02b8a1.png)
 
I'm definitely on board with avoiding red in places! childline seems to use it quite often on some pages ^^. It does seem to lend itself quite nicely to page 5? What do you think? We've stripped it off of the form pages, looks much better 😄

**Comment by SavageWilliam** [comment]
@lizziesumner  The ticks and stars on your above comment is just for us to track our progress :) ticks means we've made the changes!

**Comment by jenlittle** [comment]
@SavageWilliam I agree we do use it a lot! I've attached a few pages from our brand guide to give a little context on this - if you take a look at the last page in particular I think the "reassuring" pallette is what we would want to aim for:
[Childline Brand Guide - colour.pdf](https://github.com/FAC9/childline-yoti/files/763560/Childline.Brand.Guide.-.colour.pdf)

**Comment by SavageWilliam** [comment]
@jenlittle woah amazing!!! this is great! thanks, we'll implement the reassuring pallete 😄
