### ISSUE TITLE
Future tech stack and things to discuss

### ISSUE THREAD

**Issue by denesnori** [FAC9/childline-yoti#53]
We should provide a plan on the future tech stack in case the project is selected for further development.

Questions to discuss:
- what should happen with the reports? Save them a database (and have an "admin version/route" for the app)? Just email them to the child counsellors (or whoever handles the reports)
- for CYPs: email notification / anonymous login to track progress. of their  report.

As as we decide on this, we can come up  with the corresponding technical decisions.

**Comment by SavageWilliam** [comment]
1) I don't think we should save any reports our side? I guess once IWF receive the report.. they can choose to save it somewhere or not? @jenlittle @lizziesumner ?

2) I think we should use Yoti's 'remember_me_id' and save that in a database?? Hence if someone scans the QR code who has already used the app... they can see the progress?! havign this would also mean CYP's can track progress without receiving emails about it which they might find stressful. This leads up to require...

   - **database**
   - **email notification system**
   - added elements/functionality to handle a new **user journey** when QR code is scanned of someone WHO HAS ALREADY REPORTED? As they might actually be scanning in to report a new incident? 

## Other things to implement

- **RESPONSIVE**: Make fully responsive, currently it's poor (great for a prototype 😄 )
- **PERFORMANCE**: Improve performance regarding QR code fetching.
- **TESTS**: Wrap up in tests to add reliability to code and add longevity.
- **UX** - we could nail the UX and possibly via further consultation with childline's developers align our app more closely with their main website. 
- **User Testing** - who knows what we'll discover here 😉

**Comment by lizziesumner** [comment]
Agreed on the reporting point. We would want the IWF to hold all reports, we wouldn't want to keep them on our side or on the app.

If this idea gets selected, we can talk to the IWF about their preferred solution,

**Comment by denesnori** [comment]
I think will and me should start planning how to improve the app.

Reflecting on Will's points:

> added elements/functionality to handle a new user journey when QR code is scanned of someone WHO HAS ALREADY REPORTED? As they might actually be scanning in to report a new incident

We should save the remember me id to our database. In this case it is easy to implement that we serve different views if they had already used the app or if they were first time users. When we check the database for the remember me ID and it is not there, we return  one page, and if the id was in our database, we simply return a different page.

What is unclear to me:
- We were talking about this functionality earlier. If somebody sent a report, they should be able to login to the app and track the progesss of their claim (pizza chart).  --> It would need either sombody from childline/ IWF login to the app, and change the status of the request. --> @SavageWilliam we need  "oridinary user" routes and "counsellor" routes with different rights.  Ho can we implement this? Without asking for any personal details (for counsellor)? I have one idea in my mind...We would have two websites using the same online databse.  We sould build a different website/app for the counsellors, and they can update the status of the report (based on the remembermeID). (This second app shouldn't be open to anyone...We should make 1-3 admin users who can add new users...or registration should be based on email invitation..or something like these options)

@jenlittle , @lizziesumner what options would you like to see in the pizzachart?
I was thinking about something like this
1. report sent to childline
2. report opened and confirmed by a childline councellor
3. report sent to the cyber team
4. our team of hackers looking for the image
5. images removed

**Comment by denesnori** [comment]
@jenlittle , @lizziesumner  I also realised that we should discuss where the app should send the reports.

**Comment by lizziesumner** [comment]
@denesnori to answer all of the these questions, we would need to get confirmation from the IWF. At the moment we don't know what the different process stages are, so am reluctant to guess.  We can also talk to them about where reports should be sent.  We'll get in touch with them today and see what info we can get out of them. Hopefully it won't take too long. 

Is there anything thing else that you think  might be useful to know?

**Comment by SavageWilliam** [comment]
@denesnori good work!

Just to clarify then for @lizziesumner :

## Questions
1) How does IWF currently monitor the progress of an individual report?
2) Would IWF be able and willing to update the progress of a report if we produced a simple app to do so?
3) Location to send reports?
4) Clarify if they would like any FURTHER information than the fields we created for the prototype (url, description, image 'type').
5) Send them a link to the prototype - see what they think 😄 .

(would be really great if we could get some answers to these for Monday)

## User testing
In addition, user testing results for Monday 👍 


@lizziesumner @jenlittle Would also be really interesting to speak with someone who had gone through the process with IWF on their own. I'm not sure how feasible this is?

**Comment by SavageWilliam** [comment]
@lizziesumner @jenlittle  Hope you guys have your full workforce back this week 😄  

Let us know if you have any questions on the above. 

And we'll be in touch if theres anything else we would like to find out before next Monday.

**Comment by jenlittle** [comment]
Hi @SavageWilliam Sorry I missed the bit at the bottom of your previous message. We've asked our team to download the app so I'll be trying to get them to use the links this week.

I'm not sure that it would be possible to get in touch with someone who has used the process I'm afraid as the IWF would hold their details and their t&cs wont allow sharing personal data for this purpose. When I hear back from the IWF I'll ask if they have any case studies or other collateral that would help us get int he mindset though and see if they have any other suggestions.

**Comment by SavageWilliam** [comment]
@jenlittle Awesome, hope you're getting some useful feedback 😄 

I'm also curious to find out whether we should also offer an 'alternative' to Yoti age verification. Aka look into allowing the app to either:
1)  upload a photo of passport if on desktop/or mobile
2) take a photo of passport if on phone.
(both along side the current Yoti route)
(providing IWF would value a passport photo?)

**Comment by jenlittle** [comment]
Hi @savagewilliam, I’m not making a huge amount of progress I must confess but I promise to try and find more hours in the day ☺

I would be very happy to offer other options to age verification – allowing all the options to make this journey as use-able as possible seems sensible to me. We will confirm more when we’ve heard back from the IWF (my colleagues are chasing them)

**Comment by SavageWilliam** [comment]
This issue was moved to childline-yoti/online-content-reporter#6
