### ISSUE TITLE
Contact details

### ISSUE THREAD

**Issue by jenlittle** [FAC9/childline-yoti#74]
Hi both, I hope you had a good celebration on Friday and a nice weekend. I thought I'd better put these up this morning before I forget! 

Jen Little
jennifer.little@nspcc.org.uk
0203 772 9210 

Lizzie Sumner
elizabeth.sumner@nspcc.org.uk
0203 772 9057

**Comment by denesnori** [comment]
Thanks, Jen.
My details are:
Nora Denes
denes.nori@yahoo.com
07501513858

**Comment by SavageWilliam** [comment]
Will Savage
willsavage@hotmail.com
07799624001

**Comment by SavageWilliam** [comment]
This issue was moved to childline-yoti/online-content-reporter#7
