### ISSUE TITLE
User testing 

### ISSUE THREAD

**Issue by denesnori** [FAC9/childline-yoti#76]
## Introduction to user testing 
I can't remember whether we asked you how comfortable you are with user testing prtototype. I share two links with in case you want to read / watch videos on it. The linked materials how to do in person user testing, but it is also great if you create a survey (e.g.: on survey monkey), and share the links.
  
- [youtube video on user testing](https://www.youtube.com/watch?v=U9ZG19XTbd4)
- [article on user testing](https://library.gv.com/the-gv-research-sprint-finalize-schedule-and-complete-interview-guide-day-3-b8cddb8f931d#.82x16birz)

### Introduction for testers
- tell them you are not testing them but you are testing the usability of the current prototype
- give them some context about the app
- the introduction should be unbiased, but it should give enough context for the  testers to understand why we think it is a good idea to build the app

**Feel free to rewrite it** (both the introduction and the questions, my English essay writing skill is not the best )

### Introduction
Under 18s can report explicit online content to a Childline counsellor. However, they can olny help on condition that the young person emails them their passport to prove their age. This is an outdated and cumbersome process. This process can deter young people from reporting explicit images. Either they can feel uncomfortable to reveal their identity, or they think the process is too complicated.

The app we build tries to make this process easier. Yoti is a company specialised in identity verification. 
Before using our app, people should verify their identity with Yoti.  We use their system to check whether the user is 18 or under 18. The biggest advantage is that our app doesn't ask for any other personal details, the young person remains completely anonymous.

Yoti currently only handles passports and UK driving licenses, but within a few months they will also accept Youth Cards (**I have no idea what is the name of these cards**).  This would solve many issues since reporting explicite online images is a delicate issue, the young people might feel uncomfortable to ask their parents for their passports, while the youth cards are easily accessible for them. 

### What do we want to find out?
- Is there a clear call to action on the landing page?
- Is there a clear journey through the app?
- How did you find using the app? Is there anything about the app that made you feel uncomfortable? If so, what?
- Are there any pain points? Is anything unclear?
- Does the interface inspire confidence?
- Is there an functionality you would love to see in the app? 
- Were any of the icons unclear or confusing?
- Would you feel comfortable using this app on your own? Why or why not?

(We would like to develop the product to work on all browsers, but it would be nice to get feedback on these questions too.)
- What devices do you own? (*e.g "iphone 5, macbook air", "samsung galaxy s7, chromebook")
- (If more than one device) what device would you use *most* to browse websites?
and
- What *browser* would you usually use? (Chrome/Safari/IE/Microsoft Edge/Firefox/Other) ?

@SavageWilliam  Do anything come to your mind that we should ask apart from these questions? Do you think we should remove any of the questions? (Some of them ask for similar things with slightly different wording)

**Comment by SavageWilliam** [comment]
@denesnori Looks great! What age should we set up the heroku app for? @jenlittle @lizziesumner for now we could set it to no age limit and focus on testing the under 18 user journey?

**Comment by jenlittle** [comment]
@denesnori Thank you for this - it is really nice to see how much thought had gone in to it. We do a fair amount of user testing, but this saves us time we are extra grateful for that :-D

We'll look at getting something out to our internal team today/tomorrow to see how they get on. We may have a few under 25s in the team but I think a safer option would be to put the age up. It would be good to see both sides of the journey though - @lizziesumner what do you think about making the age 30 or 35, do you think we'd get a pretty good split then?

**Comment by lizziesumner** [comment]
I think setting it to 35 is a good idea, that will allow almost all the team to take part in testing.

**Comment by lizziesumner** [comment]
Hi @denesnori @SavageWilliam - we've got some of our team set up on Yoti and they're ready to test. Have the age restrictions been changed?

**Comment by denesnori** [comment]
I published a version of the app where the age limit is 35: 
https://childline-yoti.herokuapp.com

We have a version where the age limit is 25:
https://childline-report-image.herokuapp.com

(Will might plan to raise the age limit on this version to 50. What is your plan @SavageWilliam ?)

I've just checked both apps, both of them are working now :). Please drop us a line if any of them breaks, or if we should change the age limit.

**Comment by SavageWilliam** [comment]
@denesnori nice! 

Although its great to get feedback on the user journey of an over 17 year old, I don't think it's a user journey we need to be focusing on for now?? (At least in the second sprint we begin monday?) So for that reason I think to keep things simple and not have an age restriction for the app for now?

We can then come back to the case of over 17 later?

**Comment by denesnori** [comment]
We already used two heroku domains for the app (the one you pushed to and the one I pushed to).  Today I created a new Yoti app, too (with the proper redirect url). And changed the app.pem, and the id on my local version of the master branch, and pushed that to heroku. 

So we have two apps running on heroku now. 

The master is under50, but I checked the app got redirected to the Over18 page. So i think you haven't pushed it to heroku. 
(And I think you shouldn't now...25 and 35 are good limits I guess)

**Comment by SavageWilliam** [comment]
Alright, sounds good. 😄  

We could add the links to the readme for the meantime?

**Comment by denesnori** [comment]
Good idea! I"ll do it.

**Comment by SavageWilliam** [comment]
This issue was moved to childline-yoti/online-content-reporter#4
