### ISSUE TITLE
Question - next week's schedule

### ISSUE THREAD

**Issue by denesnori** [FAC9/childline-yoti#78]
Hi @jenlittle @lizziesumner  

I asked around at Founders and Coders, and the consensus was that I should ask for your permission
(and of course Will's) on this question since you are my product owners. 

I signed up for a hackathon organized by Science Museum’s Digital Lab, and it takes place next Monday 
and Friday. I think it is a great learning opportunity since we have to build a working prototype
solving an interesting problem in just 2 days. 

I would like to ask your perssion for going to the hackathon on Tueday-Wednesday,
 and work on the Childline-Yoti app on Saturday-Sunday instead. So I would work 5 days on you product next week,
 just not on the usual Monday-Friday 5 days.

I strongly believe that this won't affect the development of your app, and we can  deliver the app on time.
Are you okay with this?  I have already asked Will for his permission, and he is fine with it.

**Comment by lizziesumner** [comment]
Hi @denesnori - that sounds like a great opportunity, of course you should do it!

Depending if its ok with you and @SavageWilliam, we'd be happy to push the dev back another week so we start officially on the 27/2. We've go some staff sickness and looming project deadlines, so resource is tight here. We've also not had a response back from IWF yet so have not been able to progress as far as we'd like from our side.

Are you happy to move it back?

**Comment by SavageWilliam** [comment]
@lizziesumner Okay, it looks like for the most part it would be more convenient to start a week later. I'm currently looking into whether this is possible with my plans (as we'd run over a week the other side & delay receiving any funding). I'll do my best and get back to you ASAP.

**Comment by jenlittle** [comment]
@SavageWilliam if it would be an issue with funding then we can certainly work with what we have - we wouldn't want to cause any issues on that side of things. 

As it has been half term we have not gotten on as far as we would have liked this week, but we can certainly push on as much as possible when everyone is back in next week. 

Let us know, and we'll take your guidance.

**Comment by SavageWilliam** [comment]
@jenlittle It definitely seems sensible to postpone a week so that we can allow you guys time to gather all information and research before hand (and logistically for Nori). I've sent a couple of emails to find out about my own restrictions. But delaying by a week should be alright with me!

I'll get back to you here by the end of the day!

**Comment by SavageWilliam** [comment]
@jenlittle @lizziesumner @denesnori  

Im happy to start the following week (27/02/17) 😄

**Comment by denesnori** [comment]
Great, thank you :)

**Comment by jenlittle** [comment]
Thank you both! Looking forward to starting next week :-)
