### ISSUE TITLE
Deploying the "final" product

### ISSUE THREAD

**Issue by denesnori** [FAC9/childline-yoti#79]
I asked around at FAC where should we deploy the final version of the project, since it's currently under
Will's and mine heroku account.

The advice was:
- we should set up a new organisation on github, and work there during this 4 weeks.
- before deploy the final version of the website on Heroku(since it is free and easy to handle).  We should:
    - set up a new email address (you, Will, and me should have access to that account)
    - we should register that account on heroku
    - we should deploy the website to heroku from that account

@SavageWilliam  Do you have anything more to add?

**Comment by jenlittle** [comment]
Sounds good to me, let me know what you need us to do.

J

**Comment by denesnori** [comment]
Great, I think we will set up a new github organisation for the project and invite you as collaborators!

**Comment by SavageWilliam** [comment]
This issue was moved to childline-yoti/online-content-reporter#3
