### ISSUE TITLE
Tech stack planning 2

### ISSUE THREAD

**Issue by denesnori** [FAC9/childline-yoti#80]
Thing we have agreed on since the previous tech stack issue
- use promises
- build frontend with React 
- build backend with Express  (instead of hapi)
- testing with jest and tape
To make it a more valuable learning experience! 

 (I will have to show you what we are building at the hackathon today and tomorrow :D we have a react frontend, an erlang backend (and two separate heroku apps communicating via websockets))

Do you have any more ideas what we can use?

**Comment by SavageWilliam** [comment]
Can't wait to see your hackathon project! 

We could consider Redux, but probably only if we choose to implement the remember me id and hence alternative user journey. Otherwise I think we'll be fairly stateless

**Comment by denesnori** [comment]
Haha :D I was thinking about the same last night!

**Comment by SavageWilliam** [comment]
This issue was moved to childline-yoti/online-content-reporter#2
