### ISSUE TITLE
Setup a new github organization and work  there from next week

### ISSUE THREAD

**Issue by denesnori** [FAC9/childline-yoti#81]

**Comment by SavageWilliam** [comment]
@denesnori What are the requirements of this organisation?

Name?
Permissions?

**Comment by denesnori** [comment]
Nothing special really :D On you homepage, if you go the + sign, select new organization, and add the 4 of us as collaborators :D .

What organisation name you suggest? The simplest choice is childline-yoti :D I can set it up now, if it is OK for you.

**Comment by SavageWilliam** [comment]
Wicked, that name sounds good.

Now, Do you think we should build up the app from scratch (copying relevant code - html, css, js) where we need it. Might make implementing the new tech stack a little easier. Plus we'd have a nice copy of the prototype for reference still in tack?

**Comment by denesnori** [comment]
:D that's exactly  what I would suggest to do!

**Comment by SavageWilliam** [comment]
This issue was moved to childline-yoti/online-content-reporter#1
